import streamlit as st

def apply_theme():
    if "dark_mode" not in st.session_state:
        st.session_state["dark_mode"] = False

    # Catppuccin Macchiato Color Palette
    if st.session_state["dark_mode"]:
        theme = {
            "BG_COLOR": "#24273A",        
            "CARD_BG": "#363A4F",         
            "TEXT_PRIMARY": "#CAD3F5",    
            "TEXT_SECONDARY": "#A5ADCB",  
            "CHART_TEMPLATE": "plotly_dark",
            "CHART_FONT": "#CAD3F5",
            "ACCENT": "#8AADF4",          
            "BORDER": "#494D64"           
        }
    else:
        # High Contrast / Light Mode
        theme = {
            "BG_COLOR": "#FFFFFF",
            "CARD_BG": "#F0F2F6",
            "TEXT_PRIMARY": "#000000",
            "TEXT_SECONDARY": "#333333",
            "CHART_TEMPLATE": "plotly_white",
            "CHART_FONT": "#000000",
            "ACCENT": "#0055AA",
            "BORDER": "#000000"
        }

    # The "Glow Up" CSS Injection
    custom_css = f"""
    <style>
        /* 1. Import Premium Font */
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&display=swap');

        /* Apply Font Globally */
        html, body, [class*="css"] {{
            font-family: 'Inter', sans-serif !important;
            -webkit-font-smoothing: antialiased;
        }}
        
        .stApp {{
            background-color: {theme['BG_COLOR']};
            color: {theme['TEXT_PRIMARY']};
        }}

        /* 2. BUTTON GLOW UP (Tabs & Actions) */
        
        /* Primary Buttons (Selected Tabs & Generate Button) */
        button[kind="primary"] {{
            background-color: {theme['ACCENT']} !important;
            color: #FFFFFF !important; /* Forces light text */
            border-radius: 20px !important;
            border: none !important;
            box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.2) !important;
            font-weight: 800 !important;
            transition: transform 0.2s ease, filter 0.2s ease !important;
        }}
        
        /* Catch inner paragraph text generated by Streamlit */
        button[kind="primary"] p, button[kind="primary"] div {{
            color: #FFFFFF !important;
        }}

        button[kind="primary"]:hover {{
            transform: scale(1.02);
            filter: brightness(1.1);
        }}

        /* Secondary Buttons (Unselected Tabs) */
        button[kind="secondary"] {{
            background-color: {theme['CARD_BG']} !important;
            border: 1px solid rgba(255, 255, 255, 0.05) !important;
            border-radius: 20px !important;
            box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.1) !important;
            color: {theme['TEXT_SECONDARY']} !important;
            font-weight: 600 !important;
            transition: transform 0.2s ease, box-shadow 0.2s ease !important;
        }}
        
        button[kind="secondary"] p, button[kind="secondary"] div {{
            color: {theme['TEXT_SECONDARY']} !important;
        }}

        button[kind="secondary"]:hover {{
            transform: scale(1.02);
            box-shadow: 0 12px 40px 0 rgba(0, 0, 0, 0.15) !important;
        }}
        
        button[kind="secondary"]:hover p {{
            color: {theme['TEXT_PRIMARY']} !important;
        }}

        /* 3. METRIC CARDS */
        [data-testid="stMetric"] {{
            background-color: {theme['CARD_BG']};
            padding: 20px;
            border-radius: 20px;
            border: 1px solid rgba(255, 255, 255, 0.05);
            box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.1);
            transition: transform 0.2s ease;
        }}
        
        [data-testid="stMetric"]:hover {{
            transform: scale(1.02);
            box-shadow: 0 12px 40px 0 rgba(0, 0, 0, 0.15);
        }}

        [data-testid="stMetricValue"] {{
            color: {theme['TEXT_PRIMARY']} !important;
            font-weight: 800 !important;
            font-size: 2rem !important;
        }}
        
        [data-testid="stMetricLabel"] {{
            color: {theme['TEXT_SECONDARY']} !important;
            font-weight: 600 !important;
            text-transform: uppercase;
            letter-spacing: 0.8px;
            font-size: 0.8rem !important;
        }}

        /* 4. PREMIUM STATUS PILL */
        .gov-pill {{
            padding: 8px 24px;
            border-radius: 30px;
            color: #24273A;
            font-weight: 800;
            display: inline-block;
            margin-top: 5px;
            letter-spacing: 1px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
            text-transform: uppercase;
        }}

        /* 5. MOBILE RESPONSIVENESS */
        @media (max-width: 430px) {{
            [data-testid="stHorizontalBlock"] {{
                flex-wrap: wrap !important;
                gap: 12px !important;
            }}

            [data-testid="column"], [data-testid="stColumn"] {{
                min-width: 40% !important;
                flex: 1 1 calc(50% - 12px) !important;
            }}
            
            h1 {{
                font-size: 1.8rem !important;
            }}
        }}

        /* Touch Targets */
        button, input, [role="button"] {{
            min-height: 48px !important;
        }}

        /* 6. GENERAL FIXES */
        [data-testid="stChatMessageContent"] *, 
        [data-testid="stMarkdownContainer"] p, 
        .streamlit-expanderContent p {{
            color: {theme['TEXT_PRIMARY']} !important;
        }}

        code, pre {{
            background-color: {theme['BG_COLOR']} !important;
            color: {theme['ACCENT']} !important;
            border: 1px solid {theme['BORDER']} !important;
            border-radius: 6px !important;
            padding: 2px 6px !important;
            font-family: monospace !important;
        }}

        .block-container {{
            padding-top: 1rem !important;
        }}
    </style>
    """
    st.markdown(custom_css, unsafe_allow_html=True)
    return theme

FOOTER_HTML = """
<div style="text-align: center; margin-top: 60px; padding-top: 24px; border-top: 1px solid #CCCCCC; color: #333333; font-size: 13px; font-family: 'Inter', sans-serif; letter-spacing: 1.5px;">
    SMART HEALTH COMPANION • DAILY WELLNESS TRACKER
</div>
"""